# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""AgentUpdate

    AgentUpdate(;
        state=nothing,
    )

    - state::String
"""
Base.@kwdef mutable struct AgentUpdate <: OpenAPI.APIModel
    state::Union{Nothing, String} = nothing

    function AgentUpdate(state, )
        OpenAPI.validate_property(AgentUpdate, Symbol("state"), state)
        return new(state, )
    end
end # type AgentUpdate

const _property_types_AgentUpdate = Dict{Symbol,String}(Symbol("state")=>"String", )
OpenAPI.property_type(::Type{ AgentUpdate }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_AgentUpdate[name]))}

function check_required(o::AgentUpdate)
    o.state === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ AgentUpdate }, name::Symbol, val)
    if name === Symbol("state")
        OpenAPI.validate_param(name, "AgentUpdate", :enum, val, ["RUNNING", "PAUSED", "STOPPED"])
    end
end
