# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""StrategyBlueprint

    StrategyBlueprint(;
        name=nothing,
        config=nothing,
    )

    - name::String : Name of the strategy as registered in the system
    - config::Dict{String, Any}
"""
Base.@kwdef mutable struct StrategyBlueprint <: OpenAPI.APIModel
    name::Union{Nothing, String} = nothing
    config::Union{Nothing, Dict{String, Any}} = nothing

    function StrategyBlueprint(name, config, )
        OpenAPI.validate_property(StrategyBlueprint, Symbol("name"), name)
        OpenAPI.validate_property(StrategyBlueprint, Symbol("config"), config)
        return new(name, config, )
    end
end # type StrategyBlueprint

const _property_types_StrategyBlueprint = Dict{Symbol,String}(Symbol("name")=>"String", Symbol("config")=>"Dict{String, Any}", )
OpenAPI.property_type(::Type{ StrategyBlueprint }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_StrategyBlueprint[name]))}

function check_required(o::StrategyBlueprint)
    o.name === nothing && (return false)
    o.config === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ StrategyBlueprint }, name::Symbol, val)
end
